# Generated by Django 3.2.8 on 2021-11-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
